export const S = {
    app: {
        minHeight: "100vh",
        background: "linear-gradient(160deg, #0f1923 0%, #1a2a3a 60%, #0d1f2d 100%)",
        fontFamily: "'DM Sans', 'Segoe UI', sans-serif",
        color: "#e8edf2",
        maxWidth: 430,
        margin: "0 auto",
        position: "relative",
        overflow: "hidden",
    },
    header: {
        background: "rgba(255,255,255,0.03)",
        borderBottom: "1px solid rgba(255,255,255,0.08)",
        padding: "16px 20px 12px",
        display: "flex",
        alignItems: "center",
        gap: 12,
        backdropFilter: "blur(10px)",
        position: "sticky",
        top: 0,
        zIndex: 100,
    },
    logo: { fontSize: 26, lineHeight: 1 },
    headerText: { flex: 1 },
    headerTitle: {
        fontSize: 17,
        fontWeight: 700,
        letterSpacing: "-0.3px",
        color: "#fff",
    },
    headerSub: {
        fontSize: 11,
        color: "#6b8a9e",
        marginTop: 1,
    },
    nav: {
        display: "flex",
        borderBottom: "1px solid rgba(255,255,255,0.07)",
        background: "rgba(0,0,0,0.2)",
        position: "sticky",
        top: 65,
        zIndex: 99,
    },
    navBtn: (active) => ({
        flex: 1,
        padding: "11px 4px",
        fontSize: 10,
        fontWeight: active ? 700 : 500,
        color: active ? "#4fc3f7" : "#6b8a9e",
        background: "none",
        border: "none",
        borderBottom: active ? "2px solid #4fc3f7" : "2px solid transparent",
        cursor: "pointer",
        letterSpacing: "0.3px",
        textTransform: "uppercase",
        transition: "all 0.2s",
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        gap: 3,
    }),
    navIcon: { fontSize: 16 },
    page: {
        padding: "16px 16px 100px",
        minHeight: "calc(100vh - 130px)",
    },
    card: {
        background: "rgba(255,255,255,0.04)",
        border: "1px solid rgba(255,255,255,0.08)",
        borderRadius: 16,
        padding: 16,
        marginBottom: 12,
    },
    cardTitle: {
        fontSize: 12,
        fontWeight: 700,
        color: "#4fc3f7",
        letterSpacing: "0.8px",
        textTransform: "uppercase",
        marginBottom: 12,
    },
    input: {
        width: "100%",
        background: "rgba(255,255,255,0.06)",
        border: "1px solid rgba(255,255,255,0.12)",
        borderRadius: 10,
        padding: "11px 14px",
        color: "#e8edf2",
        fontSize: 14,
        outline: "none",
        boxSizing: "border-box",
    },
    btn: (color = "#4fc3f7") => ({
        background: color,
        color: "#0f1923",
        border: "none",
        borderRadius: 10,
        padding: "11px 18px",
        fontSize: 13,
        fontWeight: 700,
        cursor: "pointer",
        letterSpacing: "0.2px",
    }),
    btnOutline: {
        background: "transparent",
        color: "#4fc3f7",
        border: "1px solid #4fc3f7",
        borderRadius: 10,
        padding: "9px 16px",
        fontSize: 12,
        fontWeight: 600,
        cursor: "pointer",
    },
    tag: (color = "#4fc3f7") => ({
        display: "inline-block",
        background: `${color}22`,
        color: color,
        borderRadius: 6,
        padding: "3px 8px",
        fontSize: 11,
        fontWeight: 600,
    }),
    itemRow: {
        display: "flex",
        alignItems: "center",
        gap: 10,
        padding: "10px 0",
        borderBottom: "1px solid rgba(255,255,255,0.05)",
    },
    check: (done) => ({
        width: 22,
        height: 22,
        borderRadius: 6,
        border: done ? "none" : "2px solid rgba(255,255,255,0.2)",
        background: done ? "#4fc3f7" : "transparent",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        cursor: "pointer",
        flexShrink: 0,
        fontSize: 13,
    }),
    badge: {
        background: "#ff6b6b",
        color: "#fff",
        borderRadius: "50%",
        width: 18,
        height: 18,
        fontSize: 10,
        fontWeight: 700,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        flexShrink: 0,
    },
    modal: {
        position: "fixed",
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        background: "rgba(0,0,0,0.85)",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        zIndex: 1000,
        padding: 20,
    },
    modalContent: {
        background: "#1a2a3a",
        border: "1px solid rgba(255,255,255,0.12)",
        borderRadius: 20,
        padding: 24,
        maxWidth: 380,
        width: "100%",
        maxHeight: "80vh",
        overflowY: "auto",
    },
    modalTitle: {
        fontSize: 18,
        fontWeight: 700,
        marginBottom: 16,
        color: "#fff",
    },
};
